resources:
  jobs:
    my_two_task_job:
      name: prod-ingest-and-transform-job
      tasks:
        - task_key: ingest_task
          notebook_task:
            notebook_path: ./prod_vk_bundle.ipynb

        - task_key: transform_task
          depends_on:
            - task_key: ingest_task
          notebook_task:
            notebook_path: ./prod_vk_ingestion.ipynb